# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  # General pre-commit hooks for code quality
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
        args: ["--markdown-linebreak-ext=md"]
      - id: end-of-file-fixer
      - id: check-yaml
        args: ["--unsafe"] # Allow custom YAML tags
      - id: check-toml
      - id: check-json
      - id: check-added-large-files
        args: ["--maxkb=1000"]
      - id: check-merge-conflict
      - id: check-case-conflict
      - id: mixed-line-ending
        args: ["--fix=lf"]
      - id: detect-private-key
  - repo: https://github.com/rockmagma02/rust-pre-commit-hooks
    rev: v0.2.0
    hooks:
      - id: cargo-fmt
      - id: clippy
        args: ["--all-targets", "--all-features", "--", "-D", "warnings"]
  # Nix formatting (if using Nix)
  - repo: https://github.com/nix-community/nixpkgs-fmt
    rev: v1.3.0
    hooks:
      - id: nixpkgs-fmt
        files: \.nix$
  # Additional Rust tooling checks
  # Commit message formatting
  - repo: https://github.com/compilerla/conventional-pre-commit
    rev: v3.0.0
    hooks:
      - id: conventional-pre-commit
        stages: [commit-msg]
  # YAML and JSON formatting
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v4.0.0-alpha.8
    hooks:
      - id: prettier
        files: \.(json|jsonc|yaml|yml|md)$
        exclude: ^(CHANGELOG\.md|Cargo\.lock|.*\.min\.(js|css))$
  # Spellchecking for documentation
  - repo: https://github.com/crate-ci/typos
    rev: v1.16.23
    hooks:
      - id: typos
        args: [--format=brief]
        exclude: ^(Cargo\.lock|target/|\.git/)
# Configuration for specific hooks
ci:
  autofix_commit_msg: |
    [pre-commit.ci] auto fixes from pre-commit.com hooks

    for more information, see https://pre-commit.ci
  autofix_prs: true
  autoupdate_branch: ""
  autoupdate_commit_msg: "[pre-commit.ci] pre-commit autoupdate"
  autoupdate_schedule: weekly
  skip: [cargo-audit, cargo-deny] # Skip hooks that might not be available in CI
  submodules: false
