# Default git-ai configuration
# This file contains all default values and is embedded in the binary
# Behavior configuration
behavior:
  verbose: false
# Command configurations
commands:
  commit:
    prompt: null # null means use built-in prompt
    no_confirm: false
    context:
      - "Git"
      - "Project"
      - "Agent"
      - "Interaction"
      - "Repository"
  pr:
    prompt: null # null means use built-in prompt
    no_confirm: false
    context:
      - "Git"
      - "Project"
      - "Agent"
      - "Interaction"
  merge:
    prompt: null # null means use built-in prompt
    no_confirm: false
    context:
      - "Git"
      - "Project"
      - "Agent"
      - "Interaction"
  init:
    prompt: null # null means use built-in prompt
    no_confirm: false
    context:
      - "Repository"
      - "Project"
      - "Agent"
      - "Interaction"
  ignore:
    prompt: null # null means use built-in prompt
    no_confirm: false
    context:
      - "Agent"
      - "Interaction"
      - "Repository"
# Repository dependency file patterns
repository:
  dependency_files:
    # Package managers and dependency files
    package_managers:
      # Node.js
      - "package.json"
      - "package-lock.json"
      - "yarn.lock"
      - "pnpm-lock.yaml"
      - ".nvmrc"
      - ".node-version"
      # Python
      - "requirements.txt"
      - "requirements-dev.txt"
      - "requirements/*.txt"
      - "pyproject.toml"
      - "setup.py"
      - "setup.cfg"
      - "Pipfile"
      - "Pipfile.lock"
      - "poetry.lock"
      - "conda.yaml"
      - "environment.yml"
      # Rust
      - "Cargo.toml"
      - "Cargo.lock"
      # Go
      - "go.mod"
      - "go.sum"
      - "go.work"
      - "go.work.sum"
      # Java/JVM
      - "pom.xml"
      - "build.gradle"
      - "build.gradle.kts"
      - "gradle.properties"
      - "settings.gradle"
      - "settings.gradle.kts"
      - "build.sbt"
      - "project/build.properties"
      - "project/plugins.sbt"
      # PHP
      - "composer.json"
      - "composer.lock"
      # Ruby
      - "Gemfile"
      - "Gemfile.lock"
      - "*.gemspec"
      # C#/.NET
      - "*.csproj"
      - "*.fsproj"
      - "*.vbproj"
      - "*.sln"
      - "packages.config"
      - "Directory.Build.props"
      - "Directory.Packages.props"
      - "nuget.config"
      # C/C++
      - "CMakeLists.txt"
      - "Makefile"
      - "makefile"
      - "configure.ac"
      - "configure.in"
      - "meson.build"
      - "conanfile.txt"
      - "conanfile.py"
      - "vcpkg.json"
      # Swift
      - "Package.swift"
      - "Package.resolved"
      # Dart/Flutter
      - "pubspec.yaml"
      - "pubspec.lock"
      # Scala
      - "build.sbt"
      - "project/build.properties"
      # Kotlin
      - "build.gradle.kts"
      # Haskell
      - "*.cabal"
      - "cabal.project"
      - "stack.yaml"
      - "stack.yaml.lock"
      # Elm
      - "elm.json"
      # R
      - "DESCRIPTION"
      - "renv.lock"
      # Clojure
      - "project.clj"
      - "deps.edn"
      - "shadow-cljs.edn"
    # Build and automation files
    build_files:
      # Generic build
      - "Makefile"
      - "makefile"
      - "justfile"
      - "Taskfile.yml"
      - "build.sh"
      - "build.bat"
      # Docker
      - "Dockerfile"
      - "Dockerfile.*"
      - "docker-compose.yml"
      - "docker-compose.yaml"
      - "docker-compose.*.yml"
      - "docker-compose.*.yaml"
      - ".dockerignore"
      # Nix
      - "flake.nix"
      - "flake.lock"
      - "default.nix"
      - "shell.nix"
      # Webpack/bundlers
      - "webpack.config.js"
      - "webpack.*.js"
      - "rollup.config.js"
      - "vite.config.js"
      - "vite.config.ts"
      - "esbuild.config.js"
      # Task runners
      - "gulpfile.js"
      - "Gruntfile.js"
      # CMake
      - "CMakeLists.txt"
      - "cmake/*.cmake"
    # Configuration files that affect compilation/runtime
    config_files:
      # TypeScript/JavaScript
      - "tsconfig.json"
      - "tsconfig.*.json"
      - "jsconfig.json"
      - ".babelrc"
      - ".babelrc.js"
      - "babel.config.js"
      - ".eslintrc.*"
      - "eslint.config.js"
      - ".prettierrc.*"
      - "prettier.config.js"
      # Rust
      - "rust-toolchain.toml"
      - "rust-toolchain"
      - ".rustfmt.toml"
      - "rustfmt.toml"
      - "clippy.toml"
      # Python
      - "setup.cfg"
      - "tox.ini"
      - ".flake8"
      - "mypy.ini"
      - "pytest.ini"
      - "pyproject.toml"
      # EditorConfig
      - ".editorconfig"
      # Git
      - ".gitignore"
      - ".gitattributes"
      - ".gitmodules"
    # Additional patterns (empty by default, user can extend)
    additional_patterns: []
